[tool.poetry]
name = "smart-portfolio-core"
version = "0.1.0"
description = "Backend para gestión inteligente de portafolios de inversión"
authors = ["Maria Claudia Avendaño"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2"
numpy = "^2.0"
scikit-learn = "^1.5"
yfinance = "^0.2"
fastapi = "^0.143.0"
uvicorn = "^0.54.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0"
pytest-cov = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
